#!/usr/bin/env python3
import argparse, os, stat

TEMPLATES = {
    "sh": """#!/bin/bash
# {name} - {description}
# Generated by FORGE on {date}
{action}
""",
    "py": """#!/usr/bin/env python3
# {name} - {description}
# Generated by FORGE on {date}
{action}
"""
}

def main():
    p = argparse.ArgumentParser(description="FORGE: Meta-Tool Generator")
    p.add_argument("--name", required=True, help="Tool filename (without extension)")
    p.add_argument("--type", choices=["sh","py"], default="sh", help="Script type")
    p.add_argument("--desc", default="No description", help="Tool description")
    p.add_argument("--action", required=True, help="Command(s) the tool executes")
    args = p.parse_args()

    ext = ".sh" if args.type == "sh" else ".py"
    filename = args.name + ext
    content = TEMPLATES[args.type].format(
        name=args.name,
        description=args.desc,
        action=args.action.strip(),
        date=__import__("datetime").datetime.now().strftime("%Y-%m-%d %H:%M")
    )
    with open(filename, "w") as f:
        f.write(content)
    os.chmod(filename, os.stat(filename).st_mode | stat.S_IEXEC)
    print(f"Forged: {filename}")

if __name__ == "__main__":
    main()
