#!/usr/bin/env python3
# RESURRECT - Watchdog: auto-revives any dead engine
# Generated by FORGE on 2026-07-29 06:43
import subprocess, time

ENGINES = {
    "BEACON": "BEACON.py",
    "BEACON_MEGA": "BEACON_MEGA.py",
    "VACUUM": "VACUUM.py",
    "LIVE_VACUUM": "LIVE_VACUUM.py",
    "KATANA": "KATANA.py",
    "GOD_HAND": "GOD_HAND.py"
}

while True:
    for name, script in ENGINES.items():
        result = subprocess.run(["pgrep", "-f", script], capture_output=True, text=True)
        if result.returncode != 0:
            print(f"[!] {name} dead — resurrecting...")
            subprocess.Popen(["nohup", "python", "-u", script],
                             stdout=open(f"{name.lower()}_resurrect.log", "a"),
                             stderr=subprocess.STDOUT)
    time.sleep(30)
